### ISSUE TITLE
C:\Users\berat\Downloads\Sudoku-main\Sudoku-main\keystore.properties (Sistem belirtilen dosyay� bulam�yor)

### ISSUE THREAD

**Issue by bmusalli** [Lemkinator/Sudoku#2]
hi, android studio gives an error like this while running the game. Please help with problem solving

C:\Users\berat\Downloads\Sudoku-main\Sudoku-main\keystore.properties (Sistem belirtilen dosyay� bulam�yor)

**Comment by Lemkinator** [comment]
This is my keystore file with passwords for signing the app. Of course this file is missing as i wont publish it. If you want to build the app on your system you have to remove the signingConfig from app build.gradle 
(remove https://github.com/Lemkinator/Sudoku/blob/main/app/build.gradle#L8-L10, https://github.com/Lemkinator/Sudoku/blob/main/app/build.gradle#L33-L46, https://github.com/Lemkinator/Sudoku/blob/main/app/build.gradle#L56 and https://github.com/Lemkinator/Sudoku/blob/main/app/build.gradle#L64)

**Comment by bmusalli** [comment]
thanks, my problem is solved.

20 Temmuz 2023 Perşembe tarihinde Leonard Lemke ***@***.***>
yazdı:
